### ISSUE TITLE
bootstrap label classes missing in bootstrap V5 

### ISSUE THREAD

**Issue by dport96** [morea-framework/morea#12]
In migrating to V3 I found assessment-chartjs-wod.html uses bootstrap label classes  

label-success
label-info
label-warning
label-danger

which seem to have been removed in bootstrap V5 (but I found them in bootstrap V3). I didn't find any suggested replacements in the bootstrap V5 docs so I just added them in to the style for assessment-chartjs-wod.html.

**Comment by philipmjohnson** [comment]
That sounds like the right approach. I'd like to integrate your fix into the template.  Could you either:

1. Send me a pointer to the file in your repo with these changes so I can back-port them to the template, or 
2. Make a pull request on the template repo with your fixes

Thanks!

**Comment by dport96** [comment]
I'm not sure what I did is a good way to go since wod-times.html is not part of template in V3, but here's a link to what I did:

https://github.com/dport96/ITM352/blob/main/_includes/wod-times.html

**Comment by philipmjohnson** [comment]
You're right: until Athletic Software Engineering principles are adopted universally in higher education, wod-times.html unfortunately doesn't make sense for the template morea repo.

FYI, I solved this same problem slightly differently in my own wod-times.html file:

```
<span class="h4">
  <span style="padding: 2px" class="badge bg-success">Rx: {{ include.Rx }}</span>
  <span style="padding: 2px" class="badge bg-info">Av: {{ include.Av }}</span>
  <span style="padding: 2px" class="badge bg-warning">Sd: {{ include.Sd }}</span>
  <span style="padding: 2px" class="badge bg-danger">DNF: {{ include.DNF}}</span>
</span>
```

Thanks for the link to your approach!
