### ISSUE TITLE
syntax highlighting

### ISSUE THREAD

**Issue by gisma** [morea-framework/morea#15]
@philipmjohnson first thanks for the nice framework!

I am recently struggling with the syntax highlighting while editing in framework markdown files .
that means if I take your example:

<pre>
```java
public static void main(String args[]) {
  System.out.println("Hello world");
}
```
</pre>

or as well 

```
{% highlight java %}
public static void main(String args[]) {
  System.out.println("Hello world");
}
{% endhighlight %}
```
ends up in :
```
public static void main(String args[]) {
  System.out.println("Hello world");
}
```
so  actually the result is kind of pre-formated but not highlighted at all. This occurs both with my own sites build on your template (and slightly modified)  as well as with your fresh template site.
Any suggestions?
thanks and cheers
Chris

**Comment by philipmjohnson** [comment]
@gisma I've been able to reproduce your problem. I will fiddle around with this in the next few days and post an update. Thanks for reporting this.

**Comment by philipmjohnson** [comment]
@gisma For reasons that are lost to history, I commented out the line of code that loaded the CSS definitions for highlighting at some point during the development of Morea 2.0:

https://github.com/morea-framework/morea/blob/05e1cef031292f562be03e9ce53974562df9d121/_layouts/core.html#L11-L13

I think that all you need to do is to uncomment that line (i.e. remove lines 11 and 13) from your copy of _layouts/core.html and highlighting should work correctly.

I've updated the template repo so future users shouldn't have this problem, though existing users will need to update their copy manually.

**Comment by gisma** [comment]
Thanks!
